#spring:
#  profiles:
#    active: test

server:
  port: 0 # Eureka 로부터 자동 포트 부여

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:9001/eureka

spring:
  application:
    name: promotion-service
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    slave-list:
      - name: slave-1
        url:
      - name: slave-2
        url:
    username:
    password:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

kafka:
  address: