server:
  port: 0 # Eureka 로부터 자동 포트 부여

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service/eureka

spring:
  application:
    name: product-service
  zipkin:
    base-url: http://zipkin
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    slave-list:
      slave1:
      slave2:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


kafka:
  address: